FashionForecast/FashionForecast-server

build.gradle.kts, src/test/java/com/example/fashionforecastbackend/global/RestDocsConfiguration.java, src/test/java/com/example/fashionforecastbackend/global/RestDocsTest.java, src/test/java/com/example/fashionforecastbackend/global/RestDocsTestController.java, src/test/java/com/example/fashionforecastbackend/global/RestDocsTestControllerTest.java
>
- Rest Docs 클래스 구현
- Rest Docs 자동생성 테스트 완료
>
- Rest Docs 템플릿 차주 중으로 작성 예정
close #6
=> Rest Docs 적용 및 테스트 완료

.github/workflows/cicd.yml
=> delete: cicd 제거

src/main/java/com/example/fashionforecastbackend/global/response/ApiResponse.java, src/main/java/com/example/fashionforecastbackend/global/response/ErrorResponse.java
> 
정상 응답: `ApiResponse`
오류 응답 포맷: `ErrorResponse`
>
=> feat: 응답 포맷 개발

.github/workflows/CD-EC2-Dev.yml, .github/workflows/CI-DockerHubPush.yml, Dockerfile
>
작업내용
- aws ec2 개발 어플리케이션 서버 세팅
- aws ec2 개발 mysql 서버 세팅
- ci 워크플로우 구현
- cd 워크플로우 구현
github-actions를 이용하였고 민감한 정보는 secret으로 설정해두었습니다.
ci 흐름은 아래와 같습니다.
- 현재 프로젝트 레파지토리로 체크아웃
- Java 17 환경 세팅
- 빌드 진행
- 도커허브 로그인
- 도커 빌드 진행
- 도커허브로 이미지 푸시
ci와 동일하게 github-actions를 이용합니다.
우선 개발서버쪽만 작성해두었고, cd 흐름은 아래와 같습니다.
- ec2_dev 원격 접속
- 도커허브에서 개발 이미지 pull
- docker compose를 이용한 개발 이미지 활성화
>
=> CICD 파이프라인 구현

src/main/java/com/example/fashionforecastbackend/global/error/ErrorCode.java, src/main/java/com/example/fashionforecastbackend/global/error/GeneralException.java, src/main/java/com/example/fashionforecastbackend/global/error/GlobalExceptionHandler.java
>
- 예외 핸들러:  `GlobalExceptionHandler`
- 에러 코드: `ErrorCode`
- 제너럴 예외: `GeneralException`
`GeneralException`를 상속한 커스텀 예외 클래스는 /global/error/exception 패키지에 추가하면 된다.
>
=> feat: 커스텀 예외 처리 클래스 개발

build.gradle.kts, src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java, src/test/java/com/example/fashionforecastbackend/weather/presentation/WeatherControllerTest.java
> 
cors 설정하기 위한 spring security 의존성 추가하면서 oauth2 의존성도 같이 추가했습니다!
>
=> chore: cors 설정 추가

src/main/java/com/example/fashionforecastbackend/FashionForecastBackendApplication.java, src/main/java/com/example/fashionforecastbackend/weather/domain/repository/WeatherRepository.java, src/main/java/com/example/fashionforecastbackend/weather/service/Impl/WeatherServiceImpl.java, src/test/java/com/example/fashionforecastbackend/weather/domain/repository/WeatherRepositoryTest.java
>
- 매일 새벽 5시 비동기적으로 벌크 삭제하게끔 구현
>
=> 날씨 과거 데이터 삭제 스케쥴러 구현

.github/workflows/CD-EC2-Dev.yml, src/main/java/com/example/fashionforecastbackend/weather/service/Impl/WeatherServiceImpl.java
> 
원인은 baseDate를 설정하는 부분이였습니다. 현재시간이 02시 전일경우  baseDate를 하루전날로 설정해줘야 합니다
e.g) 
기존 : 20240823 / 02 시전 => 20240823 / 23시 로 조회
수정 : 20240823 / 02 시전 => 20240822 / 23시 로 조회
> 일단은 강제로 머지하겠슴다. 나중에 확인해주세요~
=> 00시 ~ 02시 날씨 조회 안되는 부분 수정

src/docs/asciidoc/docs.adoc, src/main/java/com/example/fashionforecastbackend/global/response/ApiResponse.java, src/main/java/com/example/fashionforecastbackend/guest/domain/Guest.java, src/main/java/com/example/fashionforecastbackend/guest/domain/GuestState.java, src/main/java/com/example/fashionforecastbackend/guest/domain/repository/GuestRepository.java, src/main/java/com/example/fashionforecastbackend/guest/dto/GuestLoginRequest.java, src/main/java/com/example/fashionforecastbackend/guest/dto/GuestLoginResponse.java, src/main/java/com/example/fashionforecastbackend/guest/presentation/GuestController.java, src/main/java/com/example/fashionforecastbackend/guest/service/GuestService.java, src/main/java/com/example/fashionforecastbackend/guest/service/Impl/GuestServiceImpl.java, src/main/java/com/example/fashionforecastbackend/member/domain/Member.java, src/main/java/com/example/fashionforecastbackend/member/domain/MemberBirthday.java, src/main/java/com/example/fashionforecastbackend/member/domain/MemberGender.java, src/main/java/com/example/fashionforecastbackend/member/domain/MemberJoinType.java, src/main/java/com/example/fashionforecastbackend/member/domain/MemberRole.java, src/main/java/com/example/fashionforecastbackend/member/domain/MemberState.java, src/main/java/com/example/fashionforecastbackend/member/domain/repository/MemberRepository.java, src/main/resources/static/docs/docs.html, src/test/java/com/example/fashionforecastbackend/global/restdocs/RestDocsConfiguration.java, src/test/java/com/example/fashionforecastbackend/guest/presentation/GuestControllerTest.java, src/test/java/com/example/fashionforecastbackend/weather/presentation/WeatherControllerTest.java, src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet, src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
>
작업 내용
- Guest 로그인 구현 및 테스트
- restDocs 스니펫 템플릿 작성
- Guest 로그인 api 명세서 작성
- Member 도메인 구조 설계
>
=> Guest 로그인 구현 및 Member 도메인 설계

src/main/java/com/example/fashionforecastbackend/weather/service/Impl/WeatherServiceImpl.java, src/main/java/com/example/fashionforecastbackend/weather/util/WeatherDateTimeValidator.java
=> 시간 유효성 검증 부분 수정

src/docs/asciidoc/docs.adoc, src/main/java/com/example/fashionforecastbackend/outfit/domain/Outfit.java, src/main/java/com/example/fashionforecastbackend/outfit/domain/OutfitType.java, src/main/java/com/example/fashionforecastbackend/outfit/dto/OutfitRequest.java, src/main/java/com/example/fashionforecastbackend/outfit/presentation/OutfitController.java, src/main/java/com/example/fashionforecastbackend/outfit/service/OutfitService.java, src/main/java/com/example/fashionforecastbackend/outfit/service/impl/OutfitServiceImpl.java, src/main/java/com/example/fashionforecastbackend/recommend/domain/Recommendation.java, src/main/java/com/example/fashionforecastbackend/recommend/dto/RecommendRequest.java, src/main/java/com/example/fashionforecastbackend/tempStage/domain/TempStage.java, src/main/java/com/example/fashionforecastbackend/tempStage/domain/repository/TempStageRepository.java, src/main/resources/static/docs/docs.html, src/test/java/com/example/fashionforecastbackend/outfit/presentation/OutfitControllerTest.java, src/test/java/com/example/fashionforecastbackend/recommend/presetation/RecommendationControllerTest.java
>  온도 그룹(레벨)에 따른 디폴트 옷차림 추가를 쉽게 하기 위한 API를 만들었습니다.
참고로 잠시 개발용으로 사용될 예정입니다!
자세한 건 명세서 참고 부탁드립니다!
>
=> 개발용 디폴트 옷 추가 기능

build.gradle.kts, src/docs/asciidoc/docs.adoc, src/main/java/com/example/fashionforecastbackend/global/config/RedisConfig.java, src/main/java/com/example/fashionforecastbackend/global/config/RedisProperties.java, src/main/java/com/example/fashionforecastbackend/global/error/ErrorCode.java, src/main/java/com/example/fashionforecastbackend/global/error/exception/SearchNotExistException.java, src/main/java/com/example/fashionforecastbackend/global/response/ApiResponse.java, src/main/java/com/example/fashionforecastbackend/search/domain/Search.java, src/main/java/com/example/fashionforecastbackend/search/dto/request/SearchRequest.java, src/main/java/com/example/fashionforecastbackend/search/dto/response/SearchResponse.java, src/main/java/com/example/fashionforecastbackend/search/presentation/SearchController.java, src/main/java/com/example/fashionforecastbackend/search/service/SearchService.java, src/main/java/com/example/fashionforecastbackend/search/service/impl/SearchServiceImpl.java, src/main/java/com/example/fashionforecastbackend/search/util/SearchValidator.java, src/main/resources/static/docs/docs.html, src/test/java/com/example/fashionforecastbackend/guest/presentation/GuestControllerTest.java, src/test/java/com/example/fashionforecastbackend/outfit/presentation/OutfitControllerTest.java, src/test/java/com/example/fashionforecastbackend/recommend/presetation/RecommendationControllerTest.java, src/test/java/com/example/fashionforecastbackend/search/fixture/SearchFixture.java, src/test/java/com/example/fashionforecastbackend/search/presentation/SearchControllerTest.java, src/test/java/com/example/fashionforecastbackend/weather/presentation/WeatherControllerTest.java
>
- 최근 검색어 조회
- 최근 검색어 등록
- 최근 검색어 삭제
😵‍💫
>
=> 최근 검색어 관련 api 구현

src/main/java/com/example/fashionforecastbackend/weather/service/Impl/WeatherServiceImpl.java, src/test/java/com/example/fashionforecastbackend/weather/domain/repository/WeatherRepositoryTest.java, src/test/java/com/example/fashionforecastbackend/weather/fixture/WeatherFixture.java
>
#48
02, 05, 08 ..... 23시 이렇게 3시간 간격으로 현재시간이 예보에 포함이 안되는 오류가 있었습니다. 
baseTime 연산을 수정하니까 잘되네요
>
=> 날씨 조회 로직 수정

src/main/java/com/example/fashionforecastbackend/weather/domain/Weather.java, src/main/java/com/example/fashionforecastbackend/weather/service/Impl/WeatherServiceImpl.java
>
#50 
수정 내용
- equals() 를 수정
- getFilteredWeathers() 스트림 부분에 distinct()를 추가
>
=> 날씨 중복 조회 수정

src/main/java/com/example/fashionforecastbackend/recommend/service/impl/RecommendServiceImpl.java, src/main/java/com/example/fashionforecastbackend/tempStage/domain/repository/TempStageRepository.java
=> refactor: 온도 옵션 설정 수정

src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java
=> cors 추가 설정

src/main/java/com/example/fashionforecastbackend/recommend/service/impl/RecommendServiceImpl.java
>옷차림 객체 상의 -> 하의 -> etc 순으로 정렬
>
=> refactor: 옷차림 정렬

src/main/java/com/example/fashionforecastbackend/weather/util/WeatherDateTimeValidator.java
=> 날씨 시간 유효성 검증 수정

src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java
> #61 
클라이언트 서브 도메인 cors 허용으로 수정
>
=> 클라이언트 서브 도메인 cors 허용으로 수정

src/main/java/com/example/fashionforecastbackend/global/error/ErrorCode.java, src/main/java/com/example/fashionforecastbackend/global/error/exception/InvalidTempConditionException.java, src/main/java/com/example/fashionforecastbackend/recommend/service/impl/RecommendServiceImpl.java
>
그룹 1, 그룹 8 일때 온도 옵션 예외 처리 추가
>
=> 온도 옵션 예외 처리 추가

src/main/java/com/example/fashionforecastbackend/global/error/ErrorCode.java, src/main/java/com/example/fashionforecastbackend/recommend/service/impl/RecommendServiceImpl.java
=> refactor: 기획 사항 반영

src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java
=> refactor: cors 도메인 추가

.github/workflows/CD-EC2-Dev.yml, src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java, src/main/java/com/example/fashionforecastbackend/global/jwt/service/JwtService.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/handler/Oauth2LoginSuccessHandler.java
>
#68 
- 시큐리티 쿠키 노출 설정
- successhandler redirect uri 수정 
>
=> 시큐리티 쿠키 설정 수정 및 로그인 핸들러 수정

src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/handler/Oauth2LoginSuccessHandler.java
=> 시큐리티 cors 수정

src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java, src/main/java/com/example/fashionforecastbackend/global/jwt/filter/JwtExceptionHandlerFilter.java, src/main/java/com/example/fashionforecastbackend/global/jwt/filter/JwtFilter.java, src/main/java/com/example/fashionforecastbackend/global/jwt/handler/JwtAccessDeniedHandler.java, src/main/java/com/example/fashionforecastbackend/global/jwt/handler/JwtAuthenticationEntryPoint.java, src/main/java/com/example/fashionforecastbackend/global/jwt/service/ErrorResponseMaker.java, src/main/java/com/example/fashionforecastbackend/global/jwt/service/JwtService.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/handler/Oauth2LoginSuccessHandler.java, src/test/java/com/example/fashionforecastbackend/global/ControllerTest.java
> 
권한이 필요한 요청의 jwt 인증 필터 구현
쿠키에 있는 액세스 토큰을 가져와 검증
>
=> jwt 필터 및 예외 처리 구현

src/main/java/com/example/fashionforecastbackend/global/oauth2/handler/Oauth2LoginSuccessHandler.java
=> Oauth2 로그인 핸들러 수정

src/main/java/com/example/fashionforecastbackend/global/oauth2/handler/Oauth2LoginSuccessHandler.java
>
#90 
서브모듈의 카카오, 구글 리다이렉트 주소도 변경됐습니다~ 참고 부탁드려요
>
=> 리다이렉트 url 수정

.github/workflows/CD-EC2.yml
=> 배포 스크립트 수정

src/main/java/com/example/fashionforecastbackend/global/config/SecurityConfig.java, src/main/java/com/example/fashionforecastbackend/weather/domain/Season.java
=> 날씨 조회 오류 수정

.github/workflows/CI-CD-Backend.yml
=> 트리거 push 삭제

src/docs/asciidoc/docs.adoc, src/main/java/com/example/fashionforecastbackend/global/oauth2/CustomOauth2User.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/handler/Oauth2LoginSuccessHandler.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/service/CustomOauth2UserService.java, src/main/java/com/example/fashionforecastbackend/member/domain/Gender.java, src/main/java/com/example/fashionforecastbackend/member/domain/Member.java, src/main/java/com/example/fashionforecastbackend/member/domain/repository/MemberRepository.java, src/main/java/com/example/fashionforecastbackend/member/dto/request/MemberGenderRequest.java, src/main/java/com/example/fashionforecastbackend/member/presentation/MemberController.java, src/main/java/com/example/fashionforecastbackend/member/service/MemberService.java, src/main/java/com/example/fashionforecastbackend/member/service/impl/MemberServiceImpl.java, src/main/resources/static/docs/docs.html, src/test/java/com/example/fashionforecastbackend/member/presentation/MemberControllerTest.java
- #112 
- 새로운 유저인지 확인하기 위해 `CustomOauth2User`에 신규 유저인지 여부를 나타내는 필드를 추가했습니다.
- `CustomOauth2UserService`에서 확인하여 이 필드에 값을 넣어줍니다.
- 인증 성공 후 `Oauth2LoginSuccessHandler` 에서 리다이렉트할 때 쿼리 파라미터 `isNewMember`로 신규 유저인지 여부를 클라이언트에게 알려줍니다.
- 나머지는 명세서 참고 부탁드려요~
>
=> 사용자 성별 추가 기능

src/docs/asciidoc/docs.adoc, src/main/java/com/example/fashionforecastbackend/global/error/GlobalExceptionHandler.java, src/main/java/com/example/fashionforecastbackend/global/login/service/Impl/LoginServiceImpl.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/Oauth2Attributes.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/service/CustomOauth2UserService.java, src/main/java/com/example/fashionforecastbackend/member/domain/Member.java, src/main/java/com/example/fashionforecastbackend/member/domain/MemberJoinType.java, src/main/java/com/example/fashionforecastbackend/member/domain/MemberState.java, src/main/java/com/example/fashionforecastbackend/member/domain/constant/Gender.java, src/main/java/com/example/fashionforecastbackend/member/domain/constant/MemberJoinType.java, src/main/java/com/example/fashionforecastbackend/member/domain/constant/MemberRole.java, src/main/java/com/example/fashionforecastbackend/member/domain/constant/MemberState.java, src/main/java/com/example/fashionforecastbackend/member/domain/constant/PersonalSetting.java, src/main/java/com/example/fashionforecastbackend/member/domain/repository/MemberRepository.java, src/main/java/com/example/fashionforecastbackend/member/dto/request/MemberGenderRequest.java, src/main/java/com/example/fashionforecastbackend/member/dto/response/MemberInfoResponse.java, src/main/java/com/example/fashionforecastbackend/member/presentation/MemberController.java, src/main/java/com/example/fashionforecastbackend/member/service/MemberService.java, src/main/java/com/example/fashionforecastbackend/member/service/impl/MemberServiceImpl.java, src/main/java/com/example/fashionforecastbackend/region/domain/Address.java, src/main/resources/static/docs/docs.html, src/test/java/com/example/fashionforecastbackend/member/presentation/MemberControllerTest.java
- #67 
>
- member 도메인 패키지에 상수 항목이 많아 따로 constant 패키지 분리했습니다.
- 응답 JSON 포맷은 다음과 같습니다.
```
{
"nickname" : "홍길동",
"region": "서울시 동작구",
"outingStartTime": "오전 09시",
"outingEndTime": "오후 18시",
"tempCondition": "WARM",
"gender": "MALE"
}
``` 
>
=> 회원정보 응답 기능

src/main/java/com/example/fashionforecastbackend/global/jwt/service/JwtService.java, src/main/java/com/example/fashionforecastbackend/global/oauth2/UserDetail.java, src/main/java/com/example/fashionforecastbackend/member/presentation/MemberController.java, src/main/java/com/example/fashionforecastbackend/outfit/presentation/OutfitController.java, src/test/java/com/example/fashionforecastbackend/member/presentation/MemberControllerTest.java, src/test/java/com/example/fashionforecastbackend/outfit/presentation/OutfitControllerTest.java
=> fix: principle이 null인 문제 해결

src/main/java/com/example/fashionforecastbackend/global/oauth2/service/CustomOauth2UserService.java, src/main/java/com/example/fashionforecastbackend/member/domain/constant/PersonalSetting.java, src/main/java/com/example/fashionforecastbackend/member/dto/response/MemberInfoResponse.java
- #125 
>
추가로, 새로운 회원인지 판별하는 과정에서 성별 설정 여부도 파악하도록 수정했습니다.
=> 회원 정보 null인 경우 null 반환

.github/workflows/CI-CD-Backend.yml, src/docs/asciidoc/docs.adoc, src/main/java/com/example/fashionforecastbackend/member/domain/MemberOutfit.java, src/main/java/com/example/fashionforecastbackend/member/domain/repository/MemberOutfitRepository.java, src/main/java/com/example/fashionforecastbackend/member/dto/response/MemberOutfitGroupResponse.java, src/main/java/com/example/fashionforecastbackend/member/dto/response/MemberOutfitResponse.java, src/main/java/com/example/fashionforecastbackend/member/presentation/MemberController.java, src/main/java/com/example/fashionforecastbackend/member/service/MemberService.java, src/main/java/com/example/fashionforecastbackend/member/service/impl/MemberServiceImpl.java, src/main/resources/static/docs/docs.html, src/test/java/com/example/fashionforecastbackend/member/fixture/MemberOutfitFixture.java, src/test/java/com/example/fashionforecastbackend/member/presentation/MemberControllerTest.java, src/test/java/com/example/fashionforecastbackend/member/service/impl/MemberServiceTest.java
>
#119 
자세한 내용은 api 명세서 참고 부탁드립니다~
>
✅todo
- 메인페이지에서 현재 온도 기준 회원 옷차림 조회 api
- 회원 옷차림 수정 및 삭제 api
=> 온도 단계별 회원 옷차림 전체 조회 api

src/docs/asciidoc/docs.adoc, src/main/java/com/example/fashionforecastbackend/global/login/presentation/LoginController.java, src/main/java/com/example/fashionforecastbackend/global/login/service/Impl/LoginServiceImpl.java, src/main/java/com/example/fashionforecastbackend/global/login/service/LoginService.java, src/main/resources/static/docs/docs.html, src/test/java/com/example/fashionforecastbackend/global/login/presentation/LoginControllerTest.java
>
#137 
계정(회원) 탈퇴 api 1차 구현 완료하였습니다.
해당 api 호출 시 회원과 관련된 모든 데이터가 삭제 됩니다.
자세한 내용은 api 명세서 참고 부탁드립니다.
소셜과 연결을 끊는 과정은 배포 이후 2차로 작업할 예정입니다.
>
=> 계정(회원) 탈퇴 api/#2-컨트롤러 구현

src/main/java/com/example/fashionforecastbackend/FashionForecastBackendApplication.java, src/main/java/com/example/fashionforecastbackend/member/domain/repository/MemberRepository.java, src/main/java/com/example/fashionforecastbackend/search/UuidChecker.java, src/main/java/com/example/fashionforecastbackend/search/ValidateUuid.java, src/main/java/com/example/fashionforecastbackend/search/service/impl/SearchServiceImpl.java
>
최근 검색어 관련 모든 메서드에 uuid 검증이 필요하여, 
SearchServiceImpl 클래스에 uuid 검증 커스텀 애노테이션을 적용하였습니다
>
=> 최근 검색어 uuid 검증 로직 추가

src/main/java/com/example/fashionforecastbackend/weather/domain/Season.java
> 
1~4월에 대한 계절이 Null로 설정되는 문제를 수정하였습니다
>
=> 계절 NPE 문제 수정

src/main/java/com/example/fashionforecastbackend/weather/domain/RainTypeV2.java, src/main/java/com/example/fashionforecastbackend/weather/domain/SkyStatusV2.java, src/main/java/com/example/fashionforecastbackend/weather/service/WeatherMapperV2.java
=> 하늘 상태 및 강수 타입 에러 수정

src/main/java/com/example/fashionforecastbackend/weather/util/WeatherDateTimeValidator.java
=> 날씨 조회 검증 클래스 리팩토링

src/main/java/com/example/fashionforecastbackend/global/oauth2/service/CustomOauth2UserService.java
로그인 오류가 발생하여, oauth `@Transactional` 추가
>
=> oauth @Transactional 추가
